Feature/clear form errors
Classe-Redradix/classe-public pull request #94
Opened 2022-08-09 14:36 UTC by virgilio-redradix

With this branch we will fix two problems related to the contact form:

- when the form had errors, they didn't disappear after include the correct data, e.g. the error saying that the name is required was still visible after writing a name ([see issue in Notion](https://www.notion.so/redradixinternal/Los-errores-en-el-formulario-permanecen-aun-introduciendo-los-datos-requeridos-12415b4bc90046e4aae5a25627a03a15))
- when the form had errors, they were still visible after closing and opening the form again ([see issue in Notion](https://www.notion.so/redradixinternal/Refrescar-los-errores-cuando-cierras-el-formulario-de-contacto-cab6e5de5b114b6c8726b795430ca381))

2022-08-10 06:32 UTC, SamuelRedradix approved these changes
For my part everything ok, but it would be better if @rr21pepe  could check it ;)

2022-08-11 10:26 UTC, rr21pepe requested changes
Cambiaría lo del comentario que puse sobre las funciones tipo `removeNameError` y demás. Lo del comentario de la función `isStringValid` lo dejo a tu elección.

2022-08-11 10:26 UTC, rr21pepe commented on src/hooks/useContactForm.js
> +  const removeInterestedInOptionError = () => {
A estas funciones no las termino de ver mucha utilidad, las veo un poco redundantes... Están encapsulando una llamada al método `removeError` al cual pasándole la key que se quiere eliminar ya queda bastante clara la intención, por lo que estas funciones las eliminaría y llamaría a `removeError` directamente.

2022-08-11 10:26 UTC, rr21pepe commented on src/hooks/useContactForm.js
> +    if (!isStringValid(email)) {
Esto es solo un pequeño comentario, no es necesario cambiarlo.

La función `isStringValid` únicamente está realizando una comprobación (que es que no esté vacío), por lo que el añadir solo una función solo para eso... Creo que no aporta mucho, porque si evitamos esa llamada, en el propio `if` ya sabemos qué se está comprobando y nos podemos ahorrar el subir al método a ver qué se considera que es un string vacío. Si el método hiciese más validaciones sí que le vería sentido el sacarlo a una función. Pero ya te digo, esto es solo como un pequeño comentario.

2022-08-11 12:51 UTC, virgilio-redradix commented on src/hooks/useContactForm.js
> +  const removeInterestedInOptionError = () => {
Eliminadas las funciones intermediarias para llamar directamente a `removeError`

2022-08-11 12:52 UTC, virgilio-redradix commented on src/hooks/useContactForm.js
> +    if (!isStringValid(email)) {
Eliminada la función `isStringValid`

2022-08-12 11:02 UTC, rr21pepe approved these changes

2022-08-12 11:10 UTC, merged